import type { ComponentType, SVGProps } from "react"
import {
  Activity,
  Album,
  Archive,
  Bell,
  Bitcoin,
  Book,
  BookOpen,
  Bot,
  Box,
  Brain,
  Briefcase,
  Bug,
  Calendar,
  Camera,
  ChartColumn,
  ChartLine,
  ChartNetwork,
  ChartPie,
  CircuitBoard,
  Clapperboard,
  Clock,
  Cloud,
  CloudDownload,
  Code,
  Coffee,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Database,
  Download,
  Dumbbell,
  File,
  FileText,
  Film,
  Flame,
  Folder,
  Gamepad2,
  Gauge,
  Ghost,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  HardDrive,
  Headphones,
  Heart,
  Home,
  House,
  Image,
  Inbox,
  Key,
  Keyboard,
  Landmark,
  Laptop,
  Layers,
  LayoutDashboard,
  Library,
  Lightbulb,
  Link,
  List,
  Lock,
  Mail,
  Map,
  MemoryStick,
  MessagesSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Network,
  Newspaper,
  Package,
  Palette,
  PanelTop,
  PenTool,
  Phone,
  Pizza,
  Play,
  Plug,
  Printer,
  Puzzle,
  Radio,
  Rocket,
  Router,
  Rss,
  SatelliteDish,
  Scale,
  School,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Signal,
  Smartphone,
  Sparkles,
  Speaker,
  Star,
  Sun,
  Tablet,
  Tag,
  Terminal,
  Thermometer,
  Ticket,
  Timer,
  Tv,
  Upload,
  Usb,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  WandSparkles,
  Waves,
  Webhook,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react"

/**
 * An `icon:` value is treated as an image URL or path -- rather than a name to
 * look up -- as soon as it contains a slash or a dot.
 */
export const isImageRef = (name: string): boolean =>
  name.includes("/") || name.includes(".")

/**
 * The category icons this dashboard bundles.
 *
 * Icon names come from config.yaml, so there is nothing to tree-shake against
 * at build time: importing the whole of lucide-react to look one up by name
 * cost 163 kB gzipped, well over half the bundle. Naming them explicitly here
 * costs a few hundred bytes each and lets the bundler drop the rest.
 *
 * A name that is not listed renders nothing, and 'config.example.yaml' is
 * checked against this map by a test. Any image URL or path also works as an
 * 'icon:', which is the escape hatch for anything not covered here.
 */
export const CATEGORY_ICONS: Record<
  string,
  ComponentType<SVGProps<SVGSVGElement>>
> = {
  activity: Activity,
  album: Album,
  archive: Archive,
  bell: Bell,
  bitcoin: Bitcoin,
  book: Book,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  calendar: Calendar,
  camera: Camera,
  "chart-column": ChartColumn,
  "chart-line": ChartLine,
  "chart-network": ChartNetwork,
  "chart-pie": ChartPie,
  "circuit-board": CircuitBoard,
  clapperboard: Clapperboard,
  clock: Clock,
  cloud: Cloud,
  "cloud-download": CloudDownload,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  container: Container,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  download: Download,
  dumbbell: Dumbbell,
  file: File,
  "file-text": FileText,
  film: Film,
  flame: Flame,
  folder: Folder,
  "gamepad-2": Gamepad2,
  gauge: Gauge,
  ghost: Ghost,
  gift: Gift,
  "git-branch": GitBranch,
  globe: Globe,
  "graduation-cap": GraduationCap,
  "hard-drive": HardDrive,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  house: House,
  image: Image,
  inbox: Inbox,
  key: Key,
  keyboard: Keyboard,
  landmark: Landmark,
  laptop: Laptop,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  library: Library,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  lock: Lock,
  mail: Mail,
  map: Map,
  "memory-stick": MemoryStick,
  "messages-square": MessagesSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  network: Network,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  "panel-top": PanelTop,
  "pen-tool": PenTool,
  phone: Phone,
  pizza: Pizza,
  play: Play,
  plug: Plug,
  printer: Printer,
  puzzle: Puzzle,
  radio: Radio,
  rocket: Rocket,
  router: Router,
  rss: Rss,
  "satellite-dish": SatelliteDish,
  scale: Scale,
  school: School,
  search: Search,
  server: Server,
  settings: Settings,
  "share-2": Share2,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shopping-cart": ShoppingCart,
  shuffle: Shuffle,
  signal: Signal,
  smartphone: Smartphone,
  sparkles: Sparkles,
  speaker: Speaker,
  star: Star,
  sun: Sun,
  tablet: Tablet,
  tag: Tag,
  terminal: Terminal,
  thermometer: Thermometer,
  ticket: Ticket,
  timer: Timer,
  tv: Tv,
  upload: Upload,
  usb: Usb,
  user: User,
  users: Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  "wand-sparkles": WandSparkles,
  waves: Waves,
  webhook: Webhook,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
}
