server {
    listen 1918;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Apply aggressive caching to EVERYTHING
    location / {
        add_header Cache-Control "public, max-age=31536000, immutable";
        access_log off;
        
        # SPA Routing: fallback to index.html if file doesn't exist
        try_files $uri $uri/ /index.html;
    }
}
